package engine

import (
	"bytes"
	"log"
	"os"
	"path/filepath"
)

// generatedMarkers are the conventional banners codegen tools put at the top of
// their output. They are matched case-insensitively against the head of a file.
//
// The list is deliberately narrow. Each entry is a phrase a generator writes to
// tell humans not to edit the file; none of them plausibly opens hand-written
// source. A false positive here silently drops real findings for a whole file, so
// a marker earns its place by being a statement about the file's provenance, not
// merely a word that generators happen to use.
var generatedMarkers = [][]byte{
	[]byte("do not edit"),
	[]byte("do not modify"),
	[]byte("@generated"),
	[]byte("autogenerated"),
	[]byte("auto-generated"),
	[]byte("automatically generated"),
	[]byte("generated by"),
	[]byte("generated code"),
	[]byte("code generated"),
	[]byte("this file was generated"),
	[]byte("this file is generated"),
}

// generatedHeadBytes caps how much of a file is read and how much leading comment
// text is searched.
const generatedHeadBytes = 2048

// commentPrefixes open a line comment in some language enola indexes. `*` covers
// the continuation lines of a /* … */ block.
var commentPrefixes = []string{"#", "//", "/*", "*", "<!--", "--", ";", "%"}

// looksGenerated reports whether a file opens with a codegen banner.
//
// Only the LEADING comment block is searched — the comment and docstring lines
// before the first line of actual code. Searching a flat byte window instead was
// wrong in a way worth recording: it reached past the header into the body and
// matched ordinary prose, flagging a hand-written design document on the comment
// "# metadata is auto-generated from annotations:" and a plain module on a
// docstring reading "a structured output generated by the model". Both would then
// have had every finding in the file silently dropped. A provenance banner is
// always at the top, before any code, so that is the only place worth looking.
func looksGenerated(absPath string) bool {
	f, err := os.Open(absPath)
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }() // read-only; a close error cannot affect the verdict

	buf := make([]byte, generatedHeadBytes)
	n, _ := f.Read(buf)
	if n <= 0 {
		return false
	}

	header := leadingCommentBlock(buf[:n])
	for _, m := range generatedMarkers {
		if bytes.Contains(header, m) {
			return true
		}
	}
	return false
}

// leadingCommentBlock returns the lowercased comment/docstring text at the top of
// a file, stopping at the first line of code.
func leadingCommentBlock(head []byte) []byte {
	var out []byte
	inDoc := false
	var docDelim string

	for _, raw := range bytes.Split(head, []byte("\n")) {
		line := bytes.TrimSpace(raw)
		if inDoc {
			out = append(out, bytes.ToLower(line)...)
			out = append(out, '\n')
			if bytes.Contains(line, []byte(docDelim)) {
				inDoc = false
			}
			continue
		}
		if len(line) == 0 {
			continue // blank lines inside or around a banner are fine
		}
		// A Python/JS module docstring used as the banner. Single-line forms
		// ("""x""") open and close on the same line.
		if d := docStringDelim(line); d != "" {
			out = append(out, bytes.ToLower(line)...)
			out = append(out, '\n')
			if bytes.Count(line, []byte(d)) < 2 {
				inDoc, docDelim = true, d
			}
			continue
		}
		if !hasCommentPrefix(line) {
			break // first line of code — the header is over
		}
		out = append(out, bytes.ToLower(line)...)
		out = append(out, '\n')
	}
	return out
}

func docStringDelim(line []byte) string {
	for _, d := range []string{`"""`, `'''`} {
		if bytes.HasPrefix(line, []byte(d)) {
			return d
		}
	}
	return ""
}

func hasCommentPrefix(line []byte) bool {
	for _, p := range commentPrefixes {
		if bytes.HasPrefix(line, []byte(p)) {
			return true
		}
	}
	return false
}

// markGeneratedFacts flags facts that came from generated files, so the dead-code
// detector can skip them.
//
// Generated code is a large, reliable source of false "dead code": a codegen tool
// emits a full API surface whether or not the project calls all of it, and the
// unused half is not a cleanup opportunity — deleting it just means regenerating
// it. One real repo had a generated client contribute 7 of 92 high-confidence
// findings, none actionable.
//
// The facts are flagged rather than dropped: they are still real symbols that
// belong in the graph (callers of generated code must resolve), so only the
// dead-code judgement changes. Detection is by content banner rather than by
// directory name, so it works for any generator and any language — enola's ignore
// globs already cover the tools that emit into a conventional generated/ dir.
func (e *Engine) markGeneratedFacts(repoPath string, startIdx int) {
	cache := map[string]bool{}
	files := 0
	marked := e.store.SetPropRange(startIdx, "generated", true, func(file string) bool {
		gen, seen := cache[file]
		if !seen {
			gen = looksGenerated(filepath.Join(repoPath, file))
			cache[file] = gen
			if gen {
				files++
			}
		}
		return gen
	})
	if marked > 0 {
		log.Printf("[engine] flagged %d facts from %d generated file(s)", marked, files)
	}
}
