package engine

import (
	"os"
	"path/filepath"
	"testing"
)

// Codegen banners must be recognised regardless of comment syntax or casing, and
// hand-written source must not be — a false positive here silently drops every
// finding for the file.
func TestLooksGenerated(t *testing.T) {
	dir := t.TempDir()
	write := func(name, content string) string {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
		return p
	}

	generated := map[string]string{
		"a.go":  "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage x\n",
		"b.py":  "# @generated by the thing\n\ndef f(): pass\n",
		"c.ts":  "/* eslint-disable */\n// This file was generated by an openapi tool\n",
		"d.py":  "# ---\n#  Welcome to Baml! To use this generated code, run:\n# ---\n",
		"e.kt":  "// AUTOGENERATED -- do not modify\n",
		"f.rmd": "// Automatically generated. Do Not Edit.\n",
	}
	for name, content := range generated {
		if !looksGenerated(write(name, content)) {
			t.Errorf("%s should be detected as generated", name)
		}
	}

	handwritten := map[string]string{
		// Mentions generation but is not a provenance banner.
		"g.py": "\"\"\"Helpers that generate report rows.\"\"\"\n\ndef generate_rows(): pass\n",
		"h.go": "// Package x builds code for the generator.\npackage x\n",
		"i.py": "def edit_document(doc):\n    return doc\n",
		"j.go": "package main\n\nfunc main() {}\n",
		// Both of these were flagged by an earlier flat-byte-window version, which
		// reached past the header into the body and matched ordinary prose. A file
		// wrongly marked generated has every finding in it silently dropped, so they
		// are pinned here: the marker sits in CODE, not in the leading comment block.
		"real_design_doc.py": "\"\"\"\nPipeline API Proposal\n=====================\n\nThis is NOT runnable code.\n\"\"\"\n\n" +
			"class Task:\n    is_a: str = None\n    # metadata is auto-generated from annotations:\n    pass\n",
		"real_module.py": "import asyncio\n\n\ndef f():\n    \"\"\"Returns\n    -------\n" +
			"    - BaseModel: a structured output generated by the model.\n    \"\"\"\n    return None\n",
	}
	for name, content := range handwritten {
		if looksGenerated(write(name, content)) {
			t.Errorf("%s is hand-written but was flagged generated", name)
		}
	}

	// A banner buried far below the head is not a provenance marker.
	deep := "package x\n" + string(make([]byte, generatedHeadBytes)) + "\n// generated by tool\n"
	if looksGenerated(write("k.go", deep)) {
		t.Error("a marker past the head window must not count")
	}

	if looksGenerated(filepath.Join(dir, "missing.go")) {
		t.Error("a missing file must not be reported generated")
	}
}
