package goextractor

import (
	"go/ast"
	"go/token"
	"regexp"
	"strconv"
	"strings"

	"github.com/enola-labs/enola/internal/facts"
)

var (
	reCreateTable = regexp.MustCompile(`(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?` + "`?" + `"?'?(\w+)`)
	reInsertInto  = regexp.MustCompile(`(?i)INSERT\s+INTO\s+` + "`?" + `"?'?(\w+)`)
	reUpdate      = regexp.MustCompile(`(?i)UPDATE\s+` + "`?" + `"?'?(\w+)\s+SET\b`)
	reDeleteFrom  = regexp.MustCompile(`(?i)DELETE\s+FROM\s+` + "`?" + `"?'?(\w+)`)
	reSelectFrom  = regexp.MustCompile(`(?i)\bFROM\s+` + "`?" + `"?'?(\w+)`)
	reAlterTable  = regexp.MustCompile(`(?i)ALTER\s+TABLE\s+` + "`?" + `"?'?(\w+)`)

	// reSelectKeyword gates the FROM clause reader. See selectTables.
	reSelectKeyword = regexp.MustCompile(`(?i)\bSELECT\b`)
	// reJoinTable finds a joined table INSIDE an already-located FROM clause.
	reJoinTable = regexp.MustCompile(`(?i)\bJOIN\s+` + "`?" + `"?'?(\w+)`)
	// reClauseEnd marks where a FROM clause stops and the rest of the statement begins.
	reClauseEnd = regexp.MustCompile(`(?i)\b(WHERE|GROUP\s+BY|ORDER\s+BY|HAVING|LIMIT|OFFSET|UNION|RETURNING)\b|;`)
	// reSQLComment matches a `--` line comment inside a SQL string. See stripSQLComments.
	reSQLComment = regexp.MustCompile(`--[^\n]*`)
)

// stripSQLComments removes `-- …` line comments before the statement patterns run.
//
// A comment inside a query is prose that happens to be surrounded by SQL, so it defeats
// every gate: the literal really is SQL, it really does contain SELECT, and the words in the
// comment are still English. Real example, from a Grafana migration:
//
//	-- For SQLite we need to recreate the table with primary key. CREATE TABLE was
//	-- generated by ".schema file" command after running migration.
//
// which produced a table called `was`. Stripping them is not a heuristic — a SQL comment is
// defined not to be part of the statement, so removing it is reading the language correctly.
func stripSQLComments(s string) string { return reSQLComment.ReplaceAllString(s, "") }

// maxSQLLiteral is the largest string literal searched for SQL.
//
// Above some size a literal stops being a query and starts being a document, and a document
// contains every word eventually. Grafana embeds a ~100 KB JSON schema as one Go string;
// somewhere in it are the word SELECT and the phrases "from as" and "from by", so an
// unbounded search reports tables called `as` and `by`. No keyword gate helps, because at
// that length every keyword is present.
//
// 16 KB is measured, not guessed. Across Grafana's 6,184 Go files there are 403 literals
// containing both SELECT and a FROM clause: median 65 bytes, p99 2.9 KB, largest 6.4 KB, and
// none above 8 KB. The cap sits at 2.5x the largest real query observed, which is wide
// enough that a genuine statement hitting it would be remarkable and narrow enough to
// exclude the documents.
const maxSQLLiteral = 16 * 1024

// firstGroups adapts a single-capture regex to the table-list shape, returning the first
// capture group of every match.
func firstGroups(re *regexp.Regexp) func(string) []string {
	return func(literal string) []string {
		var out []string
		for _, m := range re.FindAllStringSubmatch(literal, -1) {
			out = append(out, m[1])
		}
		return out
	}
}

// selectTables reads the tables a SELECT statement reads: the one after FROM, plus every
// table JOINed to it.
//
// It reads the FROM CLAUSE rather than scanning the whole literal, and that is what makes
// JOIN safe to read at all. Gating on "the literal contains SELECT somewhere" is enough for
// a small query and useless for a large one: Grafana ships a 100 KB JSON schema in a single
// Go string, and somewhere in it are both the word SELECT and the phrase "join time" — so a
// literal-wide scan reports a table called `time`. Bounding the search to the span between
// FROM and the clause that ends it (WHERE, GROUP BY, …) means a distant word cannot attach
// to a query it has nothing to do with.
//
// Every FROM in the literal is read, not just the first, so a subquery's table is found too.
func selectTables(literal string) []string {
	if !selectGate(literal) {
		return nil
	}
	var tables []string
	for _, loc := range reSelectFrom.FindAllStringSubmatchIndex(literal, -1) {
		tables = append(tables, literal[loc[2]:loc[3]])

		// The FROM clause runs from the table just matched to whatever ends it. JOINs
		// inside that span belong to this query; anything after it does not.
		clause := literal[loc[3]:]
		if end := reClauseEnd.FindStringIndex(clause); end != nil {
			clause = clause[:end[0]]
		}
		for _, m := range reJoinTable.FindAllStringSubmatch(clause, -1) {
			tables = append(tables, m[1])
		}
	}
	return tables
}

// selectGate decides whether a string literal contains enough SQL for a bare FROM in it to
// mean a table.
//
// Every other pattern here names two keywords — CREATE TABLE, INSERT INTO, DELETE FROM,
// UPDATE … SET — so a literal has to be trying quite hard to match one by accident.
// reSelectFrom matched a bare `FROM <word>` anywhere in ANY string, and English uses that
// phrase constantly. Real examples, all from this repository's own help text and error
// messages, each of which became a `storage` fact for a table:
//
//	"the shape below comes from the parent commits"   -> table `the`
//	"never what came from what"                       -> table `what`
//	"telling an isolated service apart from one"      -> table `one`
//	"the revision it descends from in the graph"      -> table `in`
//
// That is worse than an imprecise finding, and differently. A finding is an opinion a
// reader weighs; a FACT is the layer everything else is computed from, and enola's central
// claim is that its facts are derived rather than guessed. A regex reading prose as SQL is
// guessing — it just happens to be a regex doing it rather than a model.
//
// The gate is the SELECT keyword itself, not a list of clause words. `WHERE`, `ORDER`,
// `GROUP` and `LIMIT` are also ordinary English, so admitting a bare FROM on their account
// would trade one class of false fact for a narrower one. The cost is a query FRAGMENT that
// carries no SELECT — a builder emitting " FROM users WHERE id = $1" — which is now missed.
// That is the right way to be wrong here: a missing fact is a gap somebody can find and
// close, while an invented one silently contradicts the graph's whole premise.
func selectGate(literal string) bool { return reSelectKeyword.MatchString(literal) }

// extractStorage walks a Go file looking for SQL table references and S3 storage patterns.
func extractStorage(fset *token.FileSet, f *ast.File, relFile, pkgDir string) []facts.Fact {
	var result []facts.Fact

	// Track seen (table, operation) pairs per file to deduplicate
	type tableOp struct{ table, op string }
	seen := make(map[tableOp]bool)

	// Check for S3 imports
	hasS3Import := false
	for _, imp := range f.Imports {
		path := strings.Trim(imp.Path.Value, `"`)
		if strings.Contains(path, "aws-sdk-go") && strings.Contains(path, "/s3") {
			hasS3Import = true
			break
		}
	}

	ast.Inspect(f, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.BasicLit:
			if node.Kind != token.STRING {
				return true
			}
			// Unquote the string literal
			val, err := strconv.Unquote(node.Value)
			if err != nil {
				// Try raw string (backtick) — already unquoted by removing backticks
				val = strings.Trim(node.Value, "`")
			}

			// A literal too large to be a query is a document; see maxSQLLiteral.
			if len(val) > maxSQLLiteral {
				return true
			}
			val = stripSQLComments(val)

			line := fset.Position(node.Pos()).Line

			// Check SQL patterns
			// Each entry names the tables its statement touches. A function rather than a
			// bare regex because SELECT needs to read a whole FROM clause (see
			// selectTables) and the others do not — expressing that as "regex plus
			// optional gate" pushed the difference into a flag and still could not
			// express reading more than one table per match.
			sqlPatterns := []struct {
				operation string
				kind      string
				tables    func(string) []string
			}{
				{"CREATE", "table", firstGroups(reCreateTable)},
				{"ALTER", "table", firstGroups(reAlterTable)},
				{"INSERT", "table_reference", firstGroups(reInsertInto)},
				{"UPDATE", "table_reference", firstGroups(reUpdate)},
				{"DELETE", "table_reference", firstGroups(reDeleteFrom)},
				{"SELECT", "table_reference", selectTables},
			}

			for _, pat := range sqlPatterns {
				for _, tableName := range pat.tables(val) {
					// Skip common SQL noise words
					if isSQLNoise(tableName) {
						continue
					}
					key := tableOp{tableName, pat.operation}
					if seen[key] {
						continue
					}
					seen[key] = true

					result = append(result, facts.Fact{
						Kind: facts.KindStorage,
						Name: tableName,
						File: relFile,
						Line: line,
						Props: map[string]any{
							"storage_kind": pat.kind,
							"operation":    pat.operation,
							"language":     "go",
						},
						Relations: []facts.Relation{
							{Kind: facts.RelDeclares, Target: pkgDir},
						},
					})
				}
			}

		case *ast.TypeSpec:
			// Detect S3 storage structs
			if !hasS3Import {
				return true
			}
			st, ok := node.Type.(*ast.StructType)
			if !ok || st.Fields == nil {
				return true
			}
			for _, field := range st.Fields.List {
				typeName := typeExprToString(field.Type)
				if strings.Contains(typeName, "s3.Client") || strings.Contains(typeName, "s3.S3") {
					result = append(result, facts.Fact{
						Kind: facts.KindStorage,
						Name: node.Name.Name,
						File: relFile,
						Line: fset.Position(node.Pos()).Line,
						Props: map[string]any{
							"storage_kind": "s3",
							"language":     "go",
						},
						Relations: []facts.Relation{
							{Kind: facts.RelDeclares, Target: pkgDir},
						},
					})
					break
				}
			}
		}
		return true
	})

	return result
}

// isSQLNoise returns true for common SQL keywords that are not table names.
func isSQLNoise(name string) bool {
	lower := strings.ToLower(name)
	switch lower {
	case "select", "from", "where", "set", "into", "values", "table",
		"index", "view", "trigger", "procedure", "function",
		"dual", "information_schema", "pg_catalog",
		// More SQL keywords that reached the capture as though they were tables, each
		// seen in real code: `as` and `by` from clause boundaries, `length` from a call
		// in a column list.
		"as", "by", "length",
		// Go's regexp is RE2 and has no atomic groups, so `CREATE TABLE (?:IF NOT
		// EXISTS )?(\w+)` backtracks out of the optional clause when the literal ENDS
		// right after it — which is what `sql = "CREATE TABLE IF NOT EXISTS "` does in
		// Grafana's xorm, where the table name is appended separately. The engine then
		// captures the keyword itself. These three make that capture recognisable as
		// the keyword it is rather than a table called `IF`.
		"if", "not", "exists":
		return true
	}
	return false
}
