package dotnetextractor

import (
	"bytes"
	"path/filepath"
	"sort"
	"strings"

	"github.com/enola-labs/enola/internal/factpath"
	"github.com/enola-labs/enola/internal/facts"
)

// ── Project index ───────────────────────────────────────────────────────────

// projectInfo is one MSBuild project: the directory it sits in and the name it
// gives the assembly. Read from the path alone — a .csproj is XML whose
// AssemblyName is usually absent (MSBuild defaults it to the file name), so
// parsing it would buy nothing the basename does not already say.
type projectInfo struct {
	dir  string
	name string
}

// buildProjectIndex indexes every .csproj by its directory, longest path first so
// projectForDir's nearest-ancestor lookup is a linear scan.
func buildProjectIndex(projFiles []string) []projectInfo {
	out := make([]projectInfo, 0, len(projFiles))
	for _, rel := range projFiles {
		rel = filepath.ToSlash(rel)
		out = append(out, projectInfo{
			dir:  factpath.Dir(rel),
			name: strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel)),
		})
	}
	sort.Slice(out, func(i, j int) bool {
		if len(out[i].dir) != len(out[j].dir) {
			return len(out[i].dir) > len(out[j].dir)
		}
		return out[i].dir < out[j].dir
	})
	return out
}

// projectForDir returns the name of the nearest enclosing project, so a module
// carries the assembly it compiles into rather than only its path.
func projectForDir(dir string, projects []projectInfo) (string, bool) {
	dir = filepath.ToSlash(dir)
	for _, p := range projects {
		if dir == p.dir || strings.HasPrefix(dir, p.dir+"/") {
			return p.name, true
		}
	}
	return "", false
}

// ── Generated source ────────────────────────────────────────────────────────

// generatedSuffixes are file-name conventions the .NET toolchain and its source
// generators use. `obj/` is already excluded by the default ignore globs; these
// catch the generated files that are checked in beside real sources.
var generatedSuffixes = []string{
	".g.cs", ".g.i.cs", ".generated.cs", ".designer.cs", ".xaml.g.cs",
}

// generatedBasenames are whole file names that are always toolchain output.
var generatedBasenames = map[string]bool{
	"assemblyinfo.cs":       true,
	"assemblyattributes.cs": true,
	"globalusings.g.cs":     true,
	"globalsuppressions.cs": true,
}

// autoGeneratedMarker is the header Roslyn, the WinForms designer and every
// well-behaved source generator emit. Only the first bytes are inspected: the
// marker is required to precede the code, and scanning a whole 40k-line generated
// interop file to confirm what its first line already said is wasted I/O.
var autoGeneratedMarker = []byte("<auto-generated")

// autoGeneratedProbe is how far into a file the marker is looked for — enough to
// clear a license header, short enough to stay a constant-time check.
const autoGeneratedProbe = 2048

// isGeneratedSource reports whether a file is toolchain output rather than
// hand-written source.
//
// Generated code is excluded because it is not architecture: it is a projection of
// something else — a .resx, a .xaml, an interop definition, a serializer shape —
// and indexing it attributes thousands of symbols and a large complexity surface
// to whichever directory the generator happened to write into. On a repository the
// size of dotnet/runtime that noise dominates the god-class, hotspot and
// complexity-outlier findings, none of which anyone can act on: the fix is in the
// generator, and the generator is not in the graph.
func isGeneratedSource(relFile string, src []byte) bool {
	base := strings.ToLower(filepath.Base(relFile))
	if generatedBasenames[base] {
		return true
	}
	for _, suf := range generatedSuffixes {
		if strings.HasSuffix(base, suf) {
			return true
		}
	}
	probe := src
	if len(probe) > autoGeneratedProbe {
		probe = probe[:autoGeneratedProbe]
	}
	return bytes.Contains(probe, autoGeneratedMarker)
}

// ── Partial-type merge ──────────────────────────────────────────────────────

// mergePartialTypes collapses the several declarations of a `partial` type into
// one symbol fact, unioning their relations.
//
// C# lets a type be split across any number of files, and real codebases lean on
// it hard — 7,740 files across the benchmark corpus declare one. Left alone, each
// half becomes its own fact under the same name, which is wrong in three separate
// ways: the symbol count is inflated by however many halves exist, the type's
// edges are scattered across facts that each look thinly connected, and every
// consumer that reads a fact's File:line gets an arbitrary one of them.
//
// Only facts the walker flagged `partial` are merged. That keeps the pass narrow:
// two same-named facts that are NOT partial are overloads or genuinely distinct
// declarations, and collapsing those would hide real structure. Same-named facts
// in different directories are never merged either — the name is directory-
// anchored, so they are different nodes by construction (the same limitation the
// C/C++ extractor's header/source merge has, for the same reason).
//
// The surviving fact is the earliest by (file, line), so the merge is a function
// of the fact set and not of the order the files were walked.
func mergePartialTypes(allFacts []facts.Fact) []facts.Fact {
	// Index the partial facts by name, keeping the first-by-(file,line) as the
	// survivor. A single pass cannot do this — the survivor may appear after a
	// fact already merged into it — so collect, choose, then rebuild.
	groups := make(map[string][]int)
	for i := range allFacts {
		f := &allFacts[i]
		if f.Kind != facts.KindSymbol {
			continue
		}
		if p, _ := f.Props["partial"].(bool); !p {
			continue
		}
		groups[f.Name] = append(groups[f.Name], i)
	}
	if len(groups) == 0 {
		return allFacts
	}

	survivor := make(map[string]int, len(groups))
	for name, idxs := range groups {
		if len(idxs) == 1 {
			continue // a lone `partial` half needs no merge
		}
		best := idxs[0]
		for _, i := range idxs[1:] {
			a, b := &allFacts[i], &allFacts[best]
			if a.File < b.File || (a.File == b.File && a.Line < b.Line) {
				best = i
			}
		}
		survivor[name] = best
	}
	if len(survivor) == 0 {
		return allFacts
	}

	// Fold every non-survivor's relations and props into its survivor.
	for name, keep := range survivor {
		dst := &allFacts[keep]
		seen := make(map[facts.Relation]bool, len(dst.Relations))
		for _, r := range dst.Relations {
			seen[r] = true
		}
		for _, i := range groups[name] {
			if i == keep {
				continue
			}
			src := &allFacts[i]
			for _, r := range src.Relations {
				if seen[r] {
					continue
				}
				seen[r] = true
				dst.Relations = append(dst.Relations, r)
			}
			mergeProps(dst.Props, src.Props)
		}
		// Relations were appended in fact order; sort so the merged fact is a
		// function of the SET of halves rather than of their file order.
		sortRelations(dst.Relations)
		dst.Props["partial_declarations"] = len(groups[name])
	}

	out := allFacts[:0]
	for i := range allFacts {
		f := &allFacts[i]
		if f.Kind == facts.KindSymbol {
			if p, _ := f.Props["partial"].(bool); p {
				if keep, ok := survivor[f.Name]; ok && keep != i {
					continue // folded into the survivor
				}
			}
		}
		out = append(out, allFacts[i])
	}
	return out
}

// mergeProps folds a non-surviving partial half's props into the survivor's.
// Boolean signals OR together (a type is abstract/sealed if any half says so, and
// the walker sees only one half's modifiers); numeric metrics take the maximum, so
// a partial method whose implementation half carries the real complexity is not
// reported at the declaration half's zero. Everything else is left alone: the
// survivor's own value stands.
func mergeProps(dst, src map[string]any) {
	for k, v := range src {
		switch val := v.(type) {
		case bool:
			if val {
				dst[k] = true
			} else if _, ok := dst[k]; !ok {
				dst[k] = false
			}
		case int:
			if cur, ok := dst[k].(int); !ok || val > cur {
				dst[k] = val
			}
		default:
			if _, ok := dst[k]; !ok {
				dst[k] = v
			}
		}
	}
}

func sortRelations(rels []facts.Relation) {
	sort.Slice(rels, func(i, j int) bool {
		if rels[i].Kind != rels[j].Kind {
			return rels[i].Kind < rels[j].Kind
		}
		return rels[i].Target < rels[j].Target
	})
}

// ── Type and import resolution ──────────────────────────────────────────────

// stdlibRoots are namespace roots that ship with the runtime rather than with the
// repository. Microsoft.* is deliberately NOT here as a whole: Microsoft.Extensions
// and Microsoft.AspNetCore are NuGet packages like any other, and calling them
// stdlib would hide every framework dependency a .NET service has.
var stdlibRoots = map[string]bool{
	"System":                true,
	"Microsoft.CSharp":      true,
	"Microsoft.VisualBasic": true,
	"Microsoft.Win32":       true,
}

// resolveCSharpTargets rewrites the placeholder edge targets the walker emitted to
// canonical "<dir>.<Type>" fact names, and classifies each using directive.
//
// This has to be a whole-fact-set pass rather than a per-file one, because C#
// resolution is not lexical the way Java's is. `using System.Text;` imports a
// NAMESPACE, so a bare `StringBuilder` names no import in particular — the
// declaring type could live in any namespace the file opened. The walker
// therefore emits bare simple names and this pass binds them against a
// project-wide index, preferring a declaration in the reference's own namespace
// and otherwise requiring the simple name to be unique.
//
// An ambiguous name resolves to NOTHING and is left as written. That is the
// conservative half of the design and it is deliberate: on a corpus this size
// `Options`, `Message` and `Result` each name dozens of unrelated types, and
// picking one would manufacture an edge between two subsystems that have never
// heard of each other. A missing edge shows up as an unresolved count; a wrong one
// is invisible and gets acted on.
func resolveCSharpTargets(allFacts []facts.Fact) {
	byFQN := make(map[string]string)     // "Ns.Type" -> "<dir>.<Type>"
	bySimple := make(map[string]string)  // "Type"    -> "<dir>.<Type>", unique only
	simpleAmbig := make(map[string]bool) //           -> seen more than once
	nsDir := make(map[string]string)     // "Ns"      -> module dir
	nsAmbig := make(map[string]bool)     //           -> declared in several dirs
	typeDir := make(map[string]string)   // "Ns.Type" -> module dir
	// Names of `partial` types, whose members were offered speculatively by
	// resolveOwnMember and have to be checked against what actually exists.
	partialTypes := make(map[string]bool)
	symbolNames := make(map[string]bool, len(allFacts))

	// methodByShortName is the set of method names this repository declares. Only
	// membership matters — see bindMemberCall, which keeps the name bare rather
	// than binding it — so the value is unused and only the key is read.
	methodByShortName := make(map[string]string)
	for i := range allFacts {
		f := &allFacts[i]
		if f.Kind != facts.KindSymbol {
			continue
		}
		symbolNames[f.Name] = true
		// Functions as well as methods. A bare call target naming a declared FREE
		// FUNCTION is as real as one naming a method, and F# is the first .NET
		// language here to have any — every F#-to-F# call was being dropped.
		if k := f.Props["symbol_kind"]; k != facts.SymbolMethod && k != facts.SymbolFunc {
			continue
		}
		short := f.Name
		if dot := strings.LastIndex(short, "."); dot >= 0 {
			short = short[dot+1:]
		}
		methodByShortName[short] = f.Name
	}

	for i := range allFacts {
		f := &allFacts[i]
		if f.Kind != facts.KindSymbol || !isTypeKind(f.Props["symbol_kind"]) {
			continue
		}
		if p, _ := f.Props["partial"].(bool); p {
			partialTypes[f.Name] = true
		}
		fqn, _ := f.Props["fqn"].(string)
		if fqn == "" {
			continue
		}
		byFQN[fqn] = f.Name

		simple := fqn
		if i := strings.LastIndex(simple, "."); i >= 0 {
			simple = simple[i+1:]
		}
		if prev, ok := bySimple[simple]; ok && prev != f.Name {
			simpleAmbig[simple] = true
		} else {
			bySimple[simple] = f.Name
		}

		dir := factpath.Dir(f.File)
		typeDir[fqn] = dir
		if ns, _ := f.Props["namespace"].(string); ns != "" {
			if prev, ok := nsDir[ns]; ok && prev != dir {
				nsAmbig[ns] = true
			} else {
				nsDir[ns] = dir
			}
		}
	}

	resolve := func(target, fromNS string) (string, bool) {
		if strings.Contains(target, ".") {
			// Written qualified in source — an FQN hit is exact, and anything else
			// is a namespace this repository does not declare.
			if canon, ok := byFQN[target]; ok {
				return canon, true
			}
			return "", false
		}
		// Same-namespace declarations win: C# resolves the enclosing namespace
		// before any using directive, so this is the language's own rule, not a
		// tie-break invented here.
		if fromNS != "" {
			if canon, ok := byFQN[fromNS+"."+target]; ok {
				return canon, true
			}
		}
		if simpleAmbig[target] {
			return "", false
		}
		if canon, ok := bySimple[target]; ok {
			return canon, true
		}
		return "", false
	}

	for i := range allFacts {
		f := &allFacts[i]
		if f.Kind == facts.KindDependency {
			classifyUsing(f, nsDir, nsAmbig, typeDir)
			continue
		}
		if f.Kind != facts.KindSymbol {
			continue
		}
		fromNS, _ := f.Props["namespace"].(string)
		kept := f.Relations[:0]
		// typeRefs collects the extra edge each resolved qualified reference owes
		// to its TYPE. Appended after the loop, since kept aliases f.Relations'
		// backing array and appending mid-iteration would overwrite unread entries.
		var typeRefs []string
		for j := range f.Relations {
			r := f.Relations[j]
			switch r.Kind {
			case facts.RelImplements, facts.RelInstantiates, facts.RelInjects:
				if canon, ok := resolve(r.Target, fromNS); ok {
					r.Target = canon
				}
			case facts.RelCalls:
				// A static call written `Type.Method()`: bind it only when Type
				// resolves to a declared type, so the edge points at a real fact.
				if dot := strings.LastIndex(r.Target, "."); dot > 0 {
					recv, method := r.Target[:dot], r.Target[dot+1:]
					if canon, ok := resolve(recv, fromNS); ok {
						r.Target = canon + "." + method
						// The qualified edge vouches for the MEMBER only: the
						// dead-code detector matches a reference by its target's
						// last segment, so `VideoRange.HDR` says nothing about
						// `VideoRange`. That left 84 of jellyfin's 137 enums
						// reading as isolated while `VideoRange.HDR` appeared at
						// 25 call sites, and did the same to any class used only
						// through static calls. Adding the type edge HERE rather
						// than at the call site is what keeps it unambiguous —
						// the receiver has just been proven to name a declared
						// type, so this can never be a bare method name.
						typeRefs = append(typeRefs, canon)
					}
					// A speculative sibling call inside a partial type: keep it
					// only if the member really was declared in one of the halves.
					if partialTypes[recv] && !symbolNames[r.Target] {
						continue
					}
					break
				}
				// A dotless target is a member call on an untracked receiver.
				bound, keep := bindMemberCall(r.Target, methodByShortName)
				if !keep {
					continue
				}
				r.Target = bound
			}
			kept = append(kept, r)
		}
		f.Relations = kept
		for _, t := range typeRefs {
			if t != f.Name && !f.HasRelation(facts.RelCalls, t) {
				f.Relations = append(f.Relations, facts.Relation{Kind: facts.RelCalls, Target: t})
			}
		}
	}
}

// bindMemberCall decides what to do with a bare method name from a call on an
// untracked receiver: keep it if the repository declares a method of that name,
// drop it otherwise.
//
// The name is deliberately kept BARE even when exactly one type declares it,
// which is where this departs from the Swift extractor's post-pass. Binding a
// unique name looks free and is not: jellyfin declares exactly one `Match`
// method, `Emby.Naming/Video.FileStackRule.Match`, while four of its five
// variable-receiver `.Match(` call sites are `Regex` — so four call sites would
// have acquired an edge into the video-stack parser. A wrong edge feeds
// impact_analysis and find_path, and is worse than the missing one it replaces.
//
// Nothing is lost by refusing to guess. The consumer this exists for — the
// dead-code detector — matches a reference by SHORT NAME, so a bare `Match`
// rescues FileStackRule.Match exactly as well as a bound target would, and the
// call graph stays honest about a receiver type it never resolved.
//
// Dropping an undeclared name is the other half, and it is the majority: every
// `.ToString()`, `.Add()` and `.GetAwaiter()` in the repository would otherwise
// become an edge to a symbol that does not exist.
func bindMemberCall(name string, methodByShortName map[string]string) (string, bool) {
	if _, declared := methodByShortName[name]; !declared {
		return "", false
	}
	return name, true
}

// isTypeKind reports whether a symbol_kind names a TYPE declaration — the only
// thing a type reference can resolve to. Members share the name index's key space
// and would otherwise let `new Foo()` bind to a method called Foo.
func isTypeKind(v any) bool {
	switch v {
	case facts.SymbolClass, facts.SymbolInterface, facts.SymbolStruct,
		facts.SymbolEnum, facts.SymbolType:
		return true
	}
	return false
}

// classifyUsing sets a using directive's source to stdlib / internal / external
// and, when internal, points its import edge at the module that declares the
// namespace.
//
// A namespace declared in more than one directory resolves to none of them. C#
// namespaces are not required to agree with the file system and routinely span
// several projects; picking one would attribute the dependency to whichever
// directory happened to be indexed first, and the choice would move when an
// unrelated file was added.
func classifyUsing(f *facts.Fact, nsDir map[string]string, nsAmbig map[string]bool, typeDir map[string]string) {
	imp, _ := f.Props["import"].(string)
	if imp == "" {
		return
	}
	// An alias (`using Repo = Acme.Data.OrderRepository;`) and a `using static`
	// name a TYPE, not a namespace, so the namespace index cannot see them. Both
	// are ordinary internal dependencies when that type is one this repository
	// declares, and reading them only against nsDir filed every one of them as
	// external.
	if dir, ok := typeDir[imp]; ok {
		f.Props["source"] = "internal"
		for j := range f.Relations {
			if f.Relations[j].Kind == facts.RelImports {
				f.Relations[j].Target = dir
			}
		}
		return
	}
	if dir, ok := nsDir[imp]; ok && !nsAmbig[imp] {
		f.Props["source"] = "internal"
		for j := range f.Relations {
			if f.Relations[j].Kind == facts.RelImports {
				f.Relations[j].Target = dir
			}
		}
		return
	}
	root := imp
	if i := strings.Index(root, "."); i >= 0 {
		root = root[:i]
	}
	if stdlibRoots[imp] || stdlibRoots[root] {
		f.Props["source"] = "stdlib"
		return
	}
	// Left as "external", the value the walker wrote.
}
