package dotnetextractor

// VB.NET — the other language that compiles to the same assemblies.
//
// Line-oriented rather than AST-driven, and that is a property of the language
// rather than a shortcut. VB terminates every construct with an explicit `End
// Class` / `End Sub`, has no braces and no expression-level ambiguity about where
// a declaration begins, so a scanner with a container stack recovers the same
// structure a parser would. (There is also no maintained tree-sitter grammar for
// it, and the vendored runtime caps at ABI 14 — see the package doc.)
//
// The measured problem: dotnet/roslyn's VB compiler is 3,652 `.vb` files, and
// 11,589 of the repository's orphans are C# symbols whose only callers live in
// them — the single largest false-positive block in the .NET corpus, larger than
// any markup format.
//
// VB is CASE-INSENSITIVE. Every keyword match here folds case; a repository that
// writes `imports` or `end sub` is legal VB and parses the same.

import (
	"path"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/enola-labs/enola/internal/facts"
)

func isVBFile(relFile string) bool {
	return strings.EqualFold(filepath.Ext(relFile), ".vb")
}

// vbGeneratedSuffixes mirror generatedSuffixes for VB's own conventions.
var vbGeneratedSuffixes = []string{".designer.vb", ".generated.vb", ".g.vb"}

func isGeneratedVB(relFile string, src string) bool {
	base := strings.ToLower(path.Base(filepath.ToSlash(relFile)))
	for _, suf := range vbGeneratedSuffixes {
		if strings.HasSuffix(base, suf) {
			return true
		}
	}
	// `My Project/` is the VB project-system folder: AssemblyInfo, Resources and
	// Settings designers, all generated.
	if strings.Contains(filepath.ToSlash(relFile), "/My Project/") {
		return true
	}
	probe := src
	if len(probe) > autoGeneratedProbe {
		probe = probe[:autoGeneratedProbe]
	}
	return strings.Contains(probe, string(autoGeneratedMarker))
}

// ── Line preparation ────────────────────────────────────────────────────────

// vbStripComment removes a `'` comment, respecting string literals. VB has no
// escape character inside a string — `""` is an embedded quote — so a simple
// in-string toggle is exact rather than approximate.
func vbStripComment(line string) string {
	inStr := false
	for i := 0; i < len(line); i++ {
		switch line[i] {
		case '"':
			inStr = !inStr
		case '\'':
			if !inStr {
				return line[:i]
			}
		}
	}
	return line
}

// vbJoinContinuations folds VB's ` _` line continuation and the implicit
// continuation left by a trailing comma, so a declaration split across lines is
// scanned as the one statement it is. Roslyn's own VB writes multi-line parameter
// lists constantly.
//
// Returns one entry per logical line, carrying the 1-based line where it started.
type vbLine struct {
	text string
	line int
}

func vbLogicalLines(src string) []vbLine {
	raw := strings.Split(src, "\n")
	out := make([]vbLine, 0, len(raw))
	for i := 0; i < len(raw); i++ {
		text := strings.TrimRight(vbStripComment(raw[i]), " \t\r")
		start := i + 1
		for strings.HasSuffix(text, " _") || strings.HasSuffix(text, ",") {
			if i+1 >= len(raw) {
				break
			}
			i++
			text = strings.TrimSuffix(text, "_")
			text = strings.TrimRight(text, " \t\r") + " " +
				strings.TrimSpace(vbStripComment(raw[i]))
			text = strings.TrimRight(text, " \t\r")
		}
		if s := strings.TrimSpace(text); s != "" {
			out = append(out, vbLine{text: s, line: start})
		}
	}
	return out
}

// ── Declaration patterns ────────────────────────────────────────────────────

// VB modifiers that may precede a declaration. Matched case-insensitively.
const vbModifiers = `(?:(?:Public|Private|Friend|Protected|Partial|Shared|Shadows|` +
	`MustInherit|NotInheritable|MustOverride|Overridable|Overrides|Overloads|` +
	`ReadOnly|WriteOnly|Default|Narrowing|Widening|Iterator|Async|Custom|Static|` +
	`Const|Dim|WithEvents|NotOverridable)\s+)*`

var (
	vbNamespace = regexp.MustCompile(`(?i)^Namespace\s+([\w.]+)`)
	vbEndNS     = regexp.MustCompile(`(?i)^End\s+Namespace\b`)

	vbType = regexp.MustCompile(`(?i)^` + vbModifiers +
		`(Class|Module|Structure|Interface|Enum)\s+([A-Za-z_]\w*)`)
	vbEndType = regexp.MustCompile(`(?i)^End\s+(Class|Module|Structure|Interface|Enum)\b`)

	vbDelegate = regexp.MustCompile(`(?i)^` + vbModifiers +
		`Delegate\s+(?:Sub|Function)\s+([A-Za-z_]\w*)`)

	vbMethod = regexp.MustCompile(`(?i)^` + vbModifiers +
		`(Sub|Function)\s+([A-Za-z_]\w*)`)
	vbEndMethod = regexp.MustCompile(`(?i)^End\s+(Sub|Function)\b`)

	vbProperty = regexp.MustCompile(`(?i)^` + vbModifiers + `Property\s+([A-Za-z_]\w*)`)
	vbEvent    = regexp.MustCompile(`(?i)^` + vbModifiers + `Event\s+([A-Za-z_]\w*)`)

	vbField = regexp.MustCompile(`(?i)^` + vbModifiers + `([A-Za-z_]\w*)\s+As\s+`)

	vbImports = regexp.MustCompile(`(?i)^Imports\s+(?:([A-Za-z_]\w*)\s*=\s*)?([\w.]+(?:\(Of\s+[\w.,\s]+\))?)`)

	vbInherits   = regexp.MustCompile(`(?i)^Inherits\s+(.+)$`)
	vbImplements = regexp.MustCompile(`(?i)^Implements\s+(.+)$`)

	// `... Implements IEquatable(Of X).Equals` on a member line.
	vbMemberImplements = regexp.MustCompile(`(?i)\bImplements\s+([\w.(), ]+)$`)
	// `... Handles button.Click` wires an event to a handler.
	vbHandles = regexp.MustCompile(`(?i)\bHandles\s+([\w.,\s]+)$`)

	vbNew       = regexp.MustCompile(`(?i)\bNew\s+([A-Za-z_][\w.]*)`)
	vbCall      = regexp.MustCompile(`\b([A-Za-z_]\w*)\s*\(`)
	vbMemberRef = regexp.MustCompile(`\.([A-Za-z_]\w*)`)
	vbQualified = regexp.MustCompile(`\b([A-Z]\w*)\.([A-Za-z_]\w*)`)

	vbDecision = regexp.MustCompile(`(?i)(^|\s)(If|ElseIf|For|While|Case|Catch)\b|\bAndAlso\b|\bOrElse\b`)
	vbLoop     = regexp.MustCompile(`(?i)^(For|While|Do)\b`)
	vbEndLoop  = regexp.MustCompile(`(?i)^(Next|Loop)\b`)
)

// vbKeywords are matched by vbCall/vbMemberRef but are syntax, not symbols.
var vbKeywords = map[string]bool{
	"if": true, "then": true, "else": true, "elseif": true, "end": true, "for": true,
	"each": true, "next": true, "while": true, "do": true, "loop": true, "select": true,
	"case": true, "try": true, "catch": true, "finally": true, "throw": true,
	"return": true, "new": true, "as": true, "of": true, "is": true, "isnot": true,
	"and": true, "or": true, "not": true, "andalso": true, "orelse": true, "xor": true,
	"nothing": true, "true": true, "false": true, "me": true, "mybase": true,
	"myclass": true, "dim": true, "let": true, "set": true, "get": true, "in": true,
	"to": true, "step": true, "with": true, "using": true, "when": true, "by": true,
	"from": true, "where": true, "order": true, "group": true, "join": true,
	"sub": true, "function": true, "property": true, "event": true, "class": true,
	"module": true, "structure": true, "interface": true, "enum": true, "delegate": true,
	"namespace": true, "imports": true, "inherits": true, "implements": true,
	"handles": true, "public": true, "private": true, "friend": true, "protected": true,
	"shared": true, "partial": true, "readonly": true, "writeonly": true, "overrides": true,
	"overridable": true, "mustinherit": true, "notinheritable": true, "optional": true,
	"byval": true, "byref": true, "paramarray": true, "addhandler": true,
	"removehandler": true, "raiseevent": true, "await": true, "yield": true,
	"cint": true, "cstr": true, "cbool": true, "ctype": true, "directcast": true,
	"trycast": true, "gettype": true, "nameof": true, "string": true, "integer": true,
	"boolean": true, "object": true, "double": true, "single": true, "long": true,
	"short": true, "byte": true, "char": true, "date": true, "decimal": true,
}

func vbIsKeyword(s string) bool { return vbKeywords[strings.ToLower(s)] }

// vbExported reports whether a declaration line is part of the public surface.
// `Friend` is VB's `internal`, so it is not exported, matching how the C# walker
// treats `internal`.
func vbExported(line string) bool {
	l := strings.ToLower(line)
	return strings.HasPrefix(l, "public ") || strings.HasPrefix(l, "protected ")
}

// vbHasModifier reports whether a declaration carries a modifier word. A plain
// token scan rather than a compiled pattern: this runs per declaration line, and
// building a regexp each time would dominate the walk.
func vbHasModifier(line, mod string) bool {
	for _, f := range strings.Fields(line) {
		if strings.EqualFold(f, mod) {
			return true
		}
	}
	return false
}

// ── Walker ──────────────────────────────────────────────────────────────────

type vbWalker struct {
	dir     string
	relFile string
	ns      []string
	types   []string // enclosing type names, innermost last
	out     []facts.Fact

	// An INDEX, not a pointer. w.out grows by append while a member body is being
	// walked, and append may move the backing array — a *facts.Fact taken before
	// that point would then address the old array and every relation added through
	// it would be silently discarded.
	member    int // index into out, or -1 between members
	loopDepth int
}

// scanVB walks one VB source file and returns its facts.
func scanVB(src, relFile string) []facts.Fact {
	rel := filepath.ToSlash(relFile)
	w := &vbWalker{dir: path.Dir(rel), relFile: rel, member: -1}

	for _, ln := range vbLogicalLines(src) {
		w.line(ln)
	}
	return w.out
}

func (w *vbWalker) typeName() string {
	if len(w.types) == 0 {
		return ""
	}
	return w.dir + "." + strings.Join(w.types, ".")
}

func (w *vbWalker) namespace() string { return strings.Join(w.ns, ".") }

// cur returns the fact new relations attach to: the member being walked, or the
// enclosing type when between members (a field initializer, an Inherits clause).
func (w *vbWalker) cur() *facts.Fact {
	if w.member >= 0 {
		return &w.out[w.member]
	}
	for i := len(w.out) - 1; i >= 0; i-- {
		if w.out[i].Kind == facts.KindSymbol && w.out[i].Name == w.typeName() {
			return &w.out[i]
		}
	}
	return nil
}

func (w *vbWalker) addRel(kind, target string) {
	f := w.cur()
	if f == nil || target == "" || target == f.Name {
		return
	}
	for _, r := range f.Relations {
		if r.Kind == kind && r.Target == target {
			return
		}
	}
	f.Relations = append(f.Relations, facts.Relation{Kind: kind, Target: target})
}

func (w *vbWalker) line(ln vbLine) {
	t := ln.text

	switch {
	case vbNamespace.MatchString(t):
		w.ns = append(w.ns, vbNamespace.FindStringSubmatch(t)[1])
		return
	case vbEndNS.MatchString(t):
		if len(w.ns) > 0 {
			w.ns = w.ns[:len(w.ns)-1]
		}
		return
	case vbEndType.MatchString(t):
		w.closeMember()
		if len(w.types) > 0 {
			w.types = w.types[:len(w.types)-1]
		}
		return
	case vbEndMethod.MatchString(t):
		w.closeMember()
		return
	}

	if m := vbImports.FindStringSubmatch(t); m != nil {
		w.emitImport(m[1], m[2], ln.line)
		return
	}
	if m := vbType.FindStringSubmatch(t); m != nil {
		w.openType(m[1], m[2], t, ln.line)
		return
	}
	if m := vbDelegate.FindStringSubmatch(t); m != nil {
		w.emitType("delegate", m[1], t, ln.line)
		return
	}
	if m := vbInherits.FindStringSubmatch(t); m != nil {
		for _, s := range vbTypeList(m[1]) {
			w.addRel(facts.RelImplements, s)
		}
		return
	}
	if m := vbImplements.FindStringSubmatch(t); m != nil && w.member < 0 {
		for _, s := range vbTypeList(m[1]) {
			w.addRel(facts.RelImplements, s)
		}
		return
	}

	// Member declarations. A Sub/Function opens a body; a Property or Event may or
	// may not, and either way its own line can carry references.
	// `New` is a keyword everywhere except here, where it names the constructor.
	if m := vbMethod.FindStringSubmatch(t); m != nil &&
		(!vbIsKeyword(m[2]) || strings.EqualFold(m[2], "New")) {
		w.openMember(m[2], t, ln.line)
		w.bodyRefs(t)
		return
	}
	if m := vbProperty.FindStringSubmatch(t); m != nil && !vbIsKeyword(m[1]) {
		w.emitMember("property", m[1], t, ln.line)
		w.bodyRefs(t)
		return
	}
	if m := vbEvent.FindStringSubmatch(t); m != nil && !vbIsKeyword(m[1]) {
		w.emitMember("event", m[1], t, ln.line)
		return
	}

	// A field or constant, only when it is part of the public surface — private
	// state is not a node anyone traverses, the same rule the C# walker applies.
	if w.member < 0 && len(w.types) > 0 {
		if m := vbField.FindStringSubmatch(t); m != nil && !vbIsKeyword(m[1]) && vbExported(t) {
			kind := "variable"
			if vbHasModifier(t, "Const") {
				kind = "constant"
			}
			w.emitMember(kind, m[1], t, ln.line)
		}
	}

	w.bodyRefs(t)
}

// vbTypeList splits an Inherits/Implements clause, dropping generic arguments so
// `IEquatable(Of GlobalImport)` targets `IEquatable`.
func vbTypeList(s string) []string {
	var out []string
	depth := 0
	cur := strings.Builder{}
	flush := func() {
		v := strings.TrimSpace(cur.String())
		cur.Reset()
		if v == "" {
			return
		}
		if i := strings.Index(strings.ToLower(v), "(of "); i >= 0 {
			v = v[:i]
		}
		v = strings.TrimSpace(v)
		if i := strings.LastIndex(v, "."); i >= 0 {
			v = v[i+1:]
		}
		if v != "" && !vbIsKeyword(v) {
			out = append(out, v)
		}
	}
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '(':
			depth++
			cur.WriteByte(s[i])
		case ')':
			depth--
			cur.WriteByte(s[i])
		case ',':
			if depth == 0 {
				flush()
				continue
			}
			cur.WriteByte(s[i])
		default:
			cur.WriteByte(s[i])
		}
	}
	flush()
	return out
}

func (w *vbWalker) emitImport(alias, pathName string, line int) {
	props := map[string]any{
		"language": "vbnet",
		"import":   pathName,
		"source":   "external", // refined by classifyUsing once the repo is indexed
	}
	if alias != "" {
		props["alias"] = alias
	}
	w.out = append(w.out, facts.Fact{
		Kind:      facts.KindDependency,
		Name:      w.dir + " -> " + pathName,
		File:      w.relFile,
		Line:      line,
		Props:     props,
		Relations: []facts.Relation{{Kind: facts.RelImports, Target: pathName}},
	})
}

func (w *vbWalker) openType(keyword, name, decl string, line int) {
	w.closeMember()
	w.emitType(strings.ToLower(keyword), name, decl, line)
	w.types = append(w.types, name)
}

// vbSymbolKind maps a VB declaration keyword onto the shared symbol_kind
// vocabulary. `Module` is VB's static class — it has no C# keyword, and calling
// it a class is what puts it in the type index that resolves bare references.
func vbSymbolKind(keyword string) string {
	switch keyword {
	case "class", "module":
		return facts.SymbolClass
	case "interface":
		return facts.SymbolInterface
	case "structure":
		return facts.SymbolStruct
	case "enum":
		return facts.SymbolEnum
	default:
		return facts.SymbolType
	}
}

func (w *vbWalker) emitType(keyword, name, decl string, line int) {
	full := name
	if len(w.types) > 0 {
		full = strings.Join(w.types, ".") + "." + name
	}
	props := map[string]any{
		"language":    "vbnet",
		"symbol_kind": vbSymbolKind(keyword),
		"exported":    vbExported(decl),
	}
	if keyword == "module" {
		props["vb_module"] = true // a static class, not a namespace
	}
	if vbHasModifier(decl, "Partial") {
		props["partial"] = true
	}
	if ns := w.namespace(); ns != "" {
		props["namespace"] = ns
		props["fqn"] = ns + "." + full
	}
	w.out = append(w.out, facts.Fact{
		Kind:      facts.KindSymbol,
		Name:      w.dir + "." + full,
		File:      w.relFile,
		Line:      line,
		Props:     props,
		Relations: []facts.Relation{{Kind: facts.RelDeclares, Target: w.dir}},
	})
}

func (w *vbWalker) memberFact(kind, name, decl string, line int) facts.Fact {
	owner := w.typeName()
	full := w.dir + "." + name
	if owner != "" {
		full = owner + "." + name
	}
	props := map[string]any{
		"language":    "vbnet",
		"symbol_kind": kind,
		"exported":    vbExported(decl),
	}
	if owner != "" {
		props["receiver"] = owner
	}
	if vbHasModifier(decl, "Shared") {
		props["static"] = true
	}
	rels := []facts.Relation{{Kind: facts.RelDeclares, Target: w.dir}}
	// `Implements IFoo.Bar` and `Handles ctl.Event` on a member line are both real
	// references: the first to the interface member it satisfies, the second to the
	// event it subscribes to. Without Handles, a WinForms handler that nothing calls
	// by name reads as dead.
	if m := vbMemberImplements.FindStringSubmatch(decl); m != nil {
		for _, s := range vbTypeList(m[1]) {
			rels = append(rels, facts.Relation{Kind: facts.RelImplements, Target: s})
		}
	}
	if m := vbHandles.FindStringSubmatch(decl); m != nil {
		for _, s := range strings.Split(m[1], ",") {
			s = strings.TrimSpace(s)
			if i := strings.LastIndex(s, "."); i >= 0 {
				s = s[i+1:]
			}
			if s != "" && !vbIsKeyword(s) {
				rels = append(rels, facts.Relation{Kind: facts.RelCalls, Target: s})
			}
		}
	}
	return facts.Fact{
		Kind:      facts.KindSymbol,
		Name:      full,
		File:      w.relFile,
		Line:      line,
		Props:     props,
		Relations: rels,
	}
}

func (w *vbWalker) emitMember(kind, name, decl string, line int) {
	w.out = append(w.out, w.memberFact(kind, name, decl, line))
}

func (w *vbWalker) openMember(name, decl string, line int) {
	w.closeMember()
	kind := facts.SymbolMethod
	if strings.EqualFold(name, "New") {
		kind = "constructor"
	}
	f := w.memberFact(kind, name, decl, line)
	f.Props["cyclomatic"] = 1
	w.out = append(w.out, f)
	w.member = len(w.out) - 1
	w.loopDepth = 0
}

func (w *vbWalker) closeMember() {
	w.member = -1
	w.loopDepth = 0
}

// bodyRefs harvests the references and complexity signals on one line.
func (w *vbWalker) bodyRefs(t string) {
	f := w.cur()
	if f == nil {
		return
	}

	if w.member >= 0 {
		mp := w.out[w.member].Props
		if n := len(vbDecision.FindAllString(t, -1)); n > 0 {
			if c, ok := mp["cyclomatic"].(int); ok {
				mp["cyclomatic"] = c + n
			}
		}
		if vbLoop.MatchString(t) {
			w.loopDepth++
			if d, _ := mp["loop_depth"].(int); w.loopDepth > d {
				mp["loop_depth"] = w.loopDepth
			}
			c, _ := mp["loop_count"].(int)
			mp["loop_count"] = c + 1
		}
		if vbEndLoop.MatchString(t) && w.loopDepth > 0 {
			w.loopDepth--
		}
	}

	for _, m := range vbNew.FindAllStringSubmatch(t, -1) {
		name := m[1]
		if i := strings.LastIndex(name, "."); i >= 0 {
			name = name[i+1:]
		}
		if !vbIsKeyword(name) {
			w.addRel(facts.RelInstantiates, name)
			if ioConstructedTypes[name] {
				w.markIO()
			}
		}
	}
	for _, m := range vbQualified.FindAllStringSubmatch(t, -1) {
		recv, member := m[1], m[2]
		if vbIsKeyword(recv) || vbIsKeyword(member) {
			continue
		}
		w.addRel(facts.RelCalls, member)
		w.addRel(facts.RelCalls, recv)
		if ioStaticTypes[recv] || ioMethods[member] {
			w.markIO()
		}
	}
	for _, m := range vbCall.FindAllStringSubmatch(t, -1) {
		if name := m[1]; !vbIsKeyword(name) {
			w.addRel(facts.RelCalls, name)
			if ioMethods[name] {
				w.markIO()
			}
		}
	}
	for _, m := range vbMemberRef.FindAllStringSubmatch(t, -1) {
		if name := m[1]; !vbIsKeyword(name) {
			w.addRel(facts.RelCalls, name)
			if ioMethods[name] {
				w.markIO()
			}
		}
	}
}

func (w *vbWalker) markIO() {
	if w.member >= 0 {
		w.out[w.member].Props["io_direct"] = true
	}
}
