package tsextractor

import (
	"testing"

	"github.com/enola-labs/enola/internal/facts"
)

// Generated @protobuf-ts service metadata (abridged from the real users.ts).
const genUsersService = `// @generated by protobuf-ts
import { ServiceType } from "@protobuf-ts/runtime-rpc";
export const UserService = new ServiceType("users.v1.UserService", [
    { name: "GetUser", options: {}, I: GetUserRequest, O: GetUserResponse },
    { name: "CreateUser", options: {}, I: CreateUserRequest, O: CreateUserResponse }
]);
`

// Generated @protobuf-ts client stub (abridged from the real users.client.ts).
const genUsersClient = `// @generated by protobuf-ts
import { UserService } from "./users";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service users.v1.UserService
 */
export class UserServiceClient implements IUserServiceClient {
    typeName = UserService.typeName;
    methods = UserService.methods;
    constructor(private readonly _transport) {}
    /**
     * @generated from protobuf rpc: GetUser(users.v1.GetUserRequest) returns (users.v1.GetUserResponse);
     */
    getUser(input, options) {
        const method = this.methods[0];
        return stackIntercept("unary", this._transport, method, options, input);
    }
    /**
     * @generated from protobuf rpc: CreateUser(users.v1.CreateUserRequest) returns (users.v1.CreateUserResponse);
     */
    createUser(input, options) {
        const method = this.methods[1];
        return stackIntercept("unary", this._transport, method, options, input);
    }
}
`

func grpcRoutes(ff []facts.Fact) []facts.Fact {
	var out []facts.Fact
	for _, f := range ff {
		if f.Kind == facts.KindRoute && f.Props["framework"] == "grpc" {
			out = append(out, f)
		}
	}
	return out
}

func hasGRPCRoute(ff []facts.Fact, name string) (facts.Fact, bool) {
	for _, f := range grpcRoutes(ff) {
		if f.Name == name {
			return f, true
		}
	}
	return facts.Fact{}, false
}

// The headline behavior: only the RPC actually called becomes a client route,
// so an uncalled RPC (GetUser) stays absent and surfaces as unused downstream.
func TestGRPCClient_OnlyCalledMethodsEmitted(t *testing.T) {
	app := `import { UserServiceClient } from "./gen/users/v1/users.client";
const transport = makeTransport();
const userService = new UserServiceClient(transport);

async function submit(name: string) {
  const response = await userService.createUser({ name });
  return response.response.user;
}
`
	ff := extractAll(t, map[string]string{
		"gen/users/v1/users.ts":        genUsersService,
		"gen/users/v1/users.client.ts": genUsersClient,
		"app.ts":                       app,
	}, false)

	routes := grpcRoutes(ff)
	if len(routes) != 1 {
		t.Fatalf("expected 1 grpc client route, got %d: %+v", len(routes), routes)
	}

	create, ok := hasGRPCRoute(ff, "/users.v1.UserService/CreateUser")
	if !ok {
		t.Fatal("missing client route /users.v1.UserService/CreateUser")
	}
	if create.Props["role"] != "client" {
		t.Errorf("role = %v, want client", create.Props["role"])
	}
	if create.Props["method"] != "POST" {
		t.Errorf("method = %v, want POST", create.Props["method"])
	}
	if create.Props["source"] != "ts-grpc-client" {
		t.Errorf("source = %v, want ts-grpc-client", create.Props["source"])
	}
	if create.Props["rpc_service"] != "users.v1.UserService" {
		t.Errorf("rpc_service = %v", create.Props["rpc_service"])
	}
	if create.Props["rpc_method"] != "CreateUser" {
		t.Errorf("rpc_method = %v", create.Props["rpc_method"])
	}

	if _, ok := hasGRPCRoute(ff, "/users.v1.UserService/GetUser"); ok {
		t.Error("GetUser is never called but was emitted as a client route")
	}
}

// A client injected as a typed constructor field is still resolved.
func TestGRPCClient_InjectedField(t *testing.T) {
	app := `import { UserServiceClient } from "./gen/users/v1/users.client";
class UserRepo {
  constructor(private readonly users: UserServiceClient) {}
  load(id: string) {
    return this.users.getUser({ userId: id });
  }
}
`
	ff := extractAll(t, map[string]string{
		"gen/users/v1/users.ts":        genUsersService,
		"gen/users/v1/users.client.ts": genUsersClient,
		"repo.ts":                      app,
	}, false)

	if _, ok := hasGRPCRoute(ff, "/users.v1.UserService/GetUser"); !ok {
		t.Fatalf("expected client route for injected client call, got %+v", grpcRoutes(ff))
	}
}

// No stubs anywhere → no gRPC routes (and no panic on a nil index).
func TestGRPCClient_NoStubsNoRoutes(t *testing.T) {
	ff := extractAll(t, map[string]string{
		"app.ts": `const x = new Foo(); x.bar({});`,
	}, false)
	if got := len(grpcRoutes(ff)); got != 0 {
		t.Fatalf("expected 0 grpc routes without stubs, got %d", got)
	}
}

// connect-es generated service definition (protoc-gen-connect-es): a plain
// object with typeName + a methods map, consumed via createClient(Service, t).
const genConnectESService = `// @generated by protoc-gen-connect-es
import { MethodKind } from "@bufbuild/protobuf";
import { GetUserRequest, GetUserResponse, CreateUserRequest, CreateUserResponse } from "./users_pb";

export const UserService = {
  typeName: "users.v1.UserService",
  methods: {
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
`

// TestConnectES_CreateClient is the versionCoverage[75] anchor test.
func TestConnectES_CreateClient(t *testing.T) {
	app := `import { createClient } from "@connectrpc/connect";
import { createConnectTransport } from "@connectrpc/connect-web";
import { UserService } from "./gen/users/v1/users_connect";

const transport = createConnectTransport({ baseUrl: "/api" });
const client = createClient(UserService, transport);

async function submit(name: string) {
  const res = await client.createUser({ name });
  return res.user;
}
`
	ff := extractAll(t, map[string]string{
		"gen/users/v1/users_connect.ts": genConnectESService,
		"app.ts":                        app,
	}, false)

	routes := grpcRoutes(ff)
	if len(routes) != 1 {
		t.Fatalf("expected 1 connect-es client route, got %d: %+v", len(routes), routes)
	}
	create, ok := hasGRPCRoute(ff, "/users.v1.UserService/CreateUser")
	if !ok {
		t.Fatalf("missing connect-es client route: %+v", routes)
	}
	if create.Props["role"] != "client" || create.Props["source"] != "ts-grpc-client" {
		t.Errorf("props = %+v", create.Props)
	}
	if _, ok := hasGRPCRoute(ff, "/users.v1.UserService/GetUser"); ok {
		t.Error("GetUser is uncalled but was emitted")
	}
}

// Classic grpc-web generated client (protoc-gen-grpc-web, TypeScript import
// style): the wire path lives in MethodDescriptor / rpcCall string literals.
const genGRPCWebClient = `import * as grpcWeb from 'grpc-web';
import * as users_pb from './users_pb';

export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;

  constructor(hostname: string, credentials?: null, options?: null) {
    this.client_ = new grpcWeb.GrpcWebClientBase(options || {});
    this.hostname_ = hostname;
  }

  methodDescriptorGetUser = new grpcWeb.MethodDescriptor(
    '/users.v1.UserService/GetUser',
    grpcWeb.MethodType.UNARY,
    users_pb.GetUserRequest,
    users_pb.GetUserResponse,
    (request: users_pb.GetUserRequest) => request.serializeBinary(),
    users_pb.GetUserResponse.deserializeBinary);

  getUser(request: users_pb.GetUserRequest, metadata: grpcWeb.Metadata | null) {
    return this.client_.unaryCall(this.hostname_ + '/users.v1.UserService/GetUser', request, metadata, this.methodDescriptorGetUser);
  }

  methodDescriptorCreateUser = new grpcWeb.MethodDescriptor(
    '/users.v1.UserService/CreateUser',
    grpcWeb.MethodType.UNARY,
    users_pb.CreateUserRequest,
    users_pb.CreateUserResponse,
    (request: users_pb.CreateUserRequest) => request.serializeBinary(),
    users_pb.CreateUserResponse.deserializeBinary);

  createUser(request: users_pb.CreateUserRequest, metadata: grpcWeb.Metadata | null) {
    return this.client_.unaryCall(this.hostname_ + '/users.v1.UserService/CreateUser', request, metadata, this.methodDescriptorCreateUser);
  }
}
`

// TestGRPCWebClient covers the classic grpc-web client family.
func TestGRPCWebClient(t *testing.T) {
	app := `import { UserServiceClient } from "./gen/UsersServiceClientPb";
import { CreateUserRequest } from "./gen/users_pb";

const client = new UserServiceClient("http://localhost:8080");

async function submit() {
  const req = new CreateUserRequest();
  return await client.createUser(req, null);
}
`
	ff := extractAll(t, map[string]string{
		"gen/UsersServiceClientPb.ts": genGRPCWebClient,
		"app.ts":                      app,
	}, false)

	routes := grpcRoutes(ff)
	if len(routes) != 1 {
		t.Fatalf("expected 1 grpc-web client route, got %d: %+v", len(routes), routes)
	}
	create, ok := hasGRPCRoute(ff, "/users.v1.UserService/CreateUser")
	if !ok {
		t.Fatalf("missing grpc-web client route: %+v", routes)
	}
	if create.Props["role"] != "client" || create.Props["source"] != "ts-grpc-client" {
		t.Errorf("props = %+v", create.Props)
	}
	if _, ok := hasGRPCRoute(ff, "/users.v1.UserService/GetUser"); ok {
		t.Error("GetUser is uncalled but was emitted")
	}
}

// createPromiseClient (connect-es v1 name) is recognized too.
func TestConnectES_CreatePromiseClient(t *testing.T) {
	app := `import { createPromiseClient } from "@connectrpc/connect";
import { UserService } from "./gen/users/v1/users_connect";

const client = createPromiseClient(UserService, transport);
await client.getUser({ userId: "1" });
`
	ff := extractAll(t, map[string]string{
		"gen/users/v1/users_connect.ts": genConnectESService,
		"app.ts":                        app,
	}, false)
	if _, ok := hasGRPCRoute(ff, "/users.v1.UserService/GetUser"); !ok {
		t.Fatalf("createPromiseClient call not detected: %+v", grpcRoutes(ff))
	}
}
