package tsextractor

import (
	"os"
	"path/filepath"
	"testing"
)

// Two generated @protobuf-ts stubs for the SAME short service name in two
// versioned proto packages — ordinary API-versioning practice, and the shape
// finding 0003 was measured on in Go.
const draV1Stub = `// @generated by protobuf-ts
import { ServiceType } from "@protobuf-ts/runtime-rpc";
export const DRAPlugin = new ServiceType("dra.v1.DRAPlugin", [
    { name: "Prepare", options: {}, I: PrepareRequest, O: PrepareResponse }
]);
`

const draV1beta1Stub = `// @generated by protobuf-ts
import { ServiceType } from "@protobuf-ts/runtime-rpc";
export const DRAPlugin = new ServiceType("dra.v1beta1.DRAPlugin", [
    { name: "Prepare", options: {}, I: PrepareRequest, O: PrepareResponse }
]);
`

// A second service in the same package, named once — what must keep resolving
// while a colliding name does not.
const nodeStub = `// @generated by protobuf-ts
import { ServiceType } from "@protobuf-ts/runtime-rpc";
export const NodeService = new ServiceType("dra.v1.NodeService", [
    { name: "Watch", options: {}, I: WatchRequest, O: WatchResponse }
]);
`

// stubIndex writes the named stubs into a temp repo and builds the index over
// them in the given order, so a test can decide the scan order.
func stubIndex(t *testing.T, ordered ...[2]string) *grpcStubIndex {
	t.Helper()
	dir := t.TempDir()
	var rel []string
	for _, pair := range ordered {
		path := filepath.Join(dir, pair[0])
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(pair[1]), 0o644); err != nil {
			t.Fatal(err)
		}
		rel = append(rel, pair[0])
	}
	return buildGRPCStubIndex(dir, rel)
}

// A service name declared in two proto packages cannot be resolved from the
// short name alone. Emitting either one is a confident answer from a failed
// derivation, and picking whichever was scanned last makes the output depend on
// file order.
func TestTSAmbiguousServiceNameResolvesToNothing(t *testing.T) {
	idx := stubIndex(t, [2]string{"gen/v1/dra.ts", draV1Stub}, [2]string{"gen/v1beta1/dra.ts", draV1beta1Stub})
	if idx != nil {
		t.Fatalf("the only service in the tree is ambiguous, so the index holds nothing: classes=%v services=%v", idx.byClass, idx.byService)
	}
}

// Order must not change the answer — that is the whole defect.
func TestTSAmbiguityIsOrderIndependent(t *testing.T) {
	forward := stubIndex(t,
		[2]string{"gen/v1/dra.ts", draV1Stub},
		[2]string{"gen/v1beta1/dra.ts", draV1beta1Stub},
		[2]string{"gen/v1/node.ts", nodeStub})
	reverse := stubIndex(t,
		[2]string{"gen/v1beta1/dra.ts", draV1beta1Stub},
		[2]string{"gen/v1/dra.ts", draV1Stub},
		[2]string{"gen/v1/node.ts", nodeStub})

	_, inForward := forward.byService["DRAPlugin"]
	_, inReverse := reverse.byService["DRAPlugin"]
	if inForward || inReverse {
		t.Fatal("neither scan order may produce a resolution")
	}
	if forward.byService["NodeService"] == nil || reverse.byService["NodeService"] == nil {
		t.Fatal("the unambiguous service resolves in either order")
	}
}

// A third declaration arriving after the ambiguity was recorded must not
// reinstate a resolution — including through the conventional name derived from
// a fully-qualified one, which is a second door into the same key.
func TestTSALaterDuplicateCannotReviveAnAmbiguousName(t *testing.T) {
	idx := stubIndex(t,
		[2]string{"gen/v1/dra.ts", draV1Stub},
		[2]string{"gen/v1beta1/dra.ts", draV1beta1Stub},
		[2]string{"gen/v1/copy/dra.ts", draV1Stub},
		[2]string{"gen/v1/node.ts", nodeStub})
	if _, present := idx.byService["DRAPlugin"]; present {
		t.Fatal("once ambiguous, a name stays unresolved")
	}
	if _, present := idx.byClass["DRAPluginClient"]; present {
		t.Fatal("the derived client name must not put back what the collision dropped")
	}
	if !idx.ambiguousService["DRAPlugin"] || !idx.ambiguousClass["DRAPluginClient"] {
		t.Fatal("both doors into the key must stay closed")
	}
}

// The fix must not cost anything where the name is unambiguous, which is every
// repository the estate measures. A service legitimately registering from two
// files under the same fully-qualified name — @protobuf-ts splits the metadata
// and the client stub — is not a collision.
func TestTSUnambiguousServicesStillResolve(t *testing.T) {
	single := stubIndex(t, [2]string{"gen/v1/dra.ts", draV1Stub})
	if svc := single.byService["DRAPlugin"]; svc == nil || svc.fq != "dra.v1.DRAPlugin" {
		t.Fatalf("a single declaration must resolve normally, got %+v", svc)
	}

	split := stubIndex(t,
		[2]string{"gen/users/v1/users.ts", genUsersService},
		[2]string{"gen/users/v1/users.client.ts", genUsersClient})
	if svc := split.byClass["UserServiceClient"]; svc == nil || svc.fq != "users.v1.UserService" {
		t.Fatalf("two files declaring one service is not ambiguous, got %+v", svc)
	}
	if svc := split.byService["UserService"]; svc == nil || svc.fq != "users.v1.UserService" {
		t.Fatalf("the service const must survive the split stub, got %+v", svc)
	}
	if len(split.ambiguousClass) != 0 || len(split.ambiguousService) != 0 {
		t.Fatalf("nothing about the split stub is ambiguous: classes=%v services=%v", split.ambiguousClass, split.ambiguousService)
	}
}

// Only the colliding name is lost: a second service in the same tree, named
// once, still resolves.
func TestTSOnlyTheCollidingEntryIsLost(t *testing.T) {
	idx := stubIndex(t,
		[2]string{"gen/v1/dra.ts", draV1Stub},
		[2]string{"gen/v1beta1/dra.ts", draV1beta1Stub},
		[2]string{"gen/v1/node.ts", nodeStub})
	if _, present := idx.byService["DRAPlugin"]; present {
		t.Fatal("the colliding name must be dropped")
	}
	if svc := idx.byService["NodeService"]; svc == nil || svc.fq != "dra.v1.NodeService" {
		t.Fatalf("a service declared once must survive, got %+v", svc)
	}
	if svc := idx.byClass["NodeServiceClient"]; svc == nil {
		t.Fatal("its conventional client name must survive too")
	}
}

// End to end: a call site against the ambiguous client emits no route at all. A
// missing edge is honest; an edge to one of two API versions is wrong half the
// time.
func TestTSAmbiguousServiceEmitsNoClientRoute(t *testing.T) {
	app := `import { DRAPlugin } from "./gen/v1/dra";
const plugin = createClient(DRAPlugin, transport);
export function prepare(req) { return plugin.prepare(req); }
`
	ff := extractAll(t, map[string]string{
		"gen/v1/dra.ts":      draV1Stub,
		"gen/v1beta1/dra.ts": draV1beta1Stub,
		"app.ts":             app,
	}, false)
	if routes := grpcRoutes(ff); len(routes) != 0 {
		t.Fatalf("an ambiguous service must emit no client route, got %+v", routes)
	}
}
