package tsextractor

import (
	"regexp"
	"strings"

	"github.com/enola-labs/enola/internal/factpath"
	"github.com/enola-labs/enola/internal/facts"
)

var (
	// apiCommentRe matches the openapi-typescript codegen API name comment header.
	// Example: // API:svc-example-api
	apiCommentRe = regexp.MustCompile(`^//\s*API:\s*(\S+)`)

	// pathKeyRe matches an OpenAPI path key inside the paths type block.
	// Example:   '/api/messaging/main/inbox': {
	pathKeyRe = regexp.MustCompile(`^\s*'(/[^']+)'\s*:`)

	// methodAvailRe matches HTTP method fields that reference an operation (i.e. are available).
	// Example:     get: operations['GetInbox']
	// NOT matched: put?: never  (unavailable methods use ?:never)
	methodAvailRe = regexp.MustCompile(`^\s*(get|post|put|patch|delete|head|options|trace)\s*:\s*operations\[`)
)

// isOpenAPITypescriptFile returns true if the source looks like an
// openapi-typescript generated file. These files export a "paths" type alias
// whose keys are URL paths mapping HTTP methods to operation types.
func isOpenAPITypescriptFile(src []byte) bool {
	// Read only the first 512 bytes for a fast check.
	limit := 512
	if len(src) < limit {
		limit = len(src)
	}
	header := string(src[:limit])
	return strings.Contains(header, "export type paths") ||
		strings.Contains(header, "oapi-ts-codegen") ||
		strings.Contains(header, "openapi-typescript")
}

// extractOpenAPITypescriptFacts parses an openapi-typescript generated file and
// returns one KindRoute fact per available HTTP operation. Facts are marked with
// role="client" because these files describe routes the TypeScript code calls on
// backend services, not routes it serves.
//
// The expected format (produced by openapi-typescript and compatible codegen tools):
//
//	// Code generated by <codegen-tool>. DO NOT EDIT.
//	// API:svc-example-api
//	export type paths = {
//	  '/api/messaging/main/inbox': {
//	    get: operations['GetInbox']  ← available
//	    put?: never                   ← not available, skip
//	  }
//	}
func extractOpenAPITypescriptFacts(src []byte, relFile string) []facts.Fact {
	if !isOpenAPITypescriptFile(src) {
		return nil
	}

	lines := strings.Split(string(src), "\n")
	specDir := factpath.Dir(relFile)

	// Extract API name from the header comment block (first non-empty comment lines).
	apiName := ""
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if !strings.HasPrefix(trimmed, "//") {
			break
		}
		if m := apiCommentRe.FindStringSubmatch(line); m != nil {
			apiName = m[1]
			break
		}
	}

	// State machine: walk lines tracking brace depth within the paths type block.
	//
	//   depth 1 — inside "export type paths = {", scanning for path keys
	//   depth 2 — inside a specific path entry, scanning for method lines
	//   depth 3+ — inside a nested sub-object (e.g. parameters: {}), skip
	inPathsBlock := false
	depth := 0
	currentPath := ""
	var result []facts.Fact

	for i, line := range lines {
		opens := strings.Count(line, "{")
		closes := strings.Count(line, "}")

		if !inPathsBlock {
			// Look for the opening of the paths type alias.
			if strings.Contains(line, "export type paths") && opens > 0 {
				inPathsBlock = true
				depth = 1
			}
			continue
		}

		switch depth {
		case 1:
			// Scan for the start of a path entry: '/some/path': {
			if m := pathKeyRe.FindStringSubmatch(line); m != nil {
				currentPath = m[1]
			}
			depth += opens - closes
			if depth <= 0 {
				inPathsBlock = false // exited the paths block
			}

		case 2:
			// Inside a path entry — look for available HTTP method declarations.
			if currentPath != "" {
				if m := methodAvailRe.FindStringSubmatch(line); m != nil {
					method := strings.ToUpper(m[1])
					props := map[string]any{
						"method":         method,
						facts.PropSource: facts.RouteSourceOpenAPITypeScript,
						facts.PropRole:   facts.RoleClient,
						"framework":      "openapi",
						"language":       "typescript",
						"spec_file":      relFile,
					}
					if apiName != "" {
						props["api"] = apiName
					}
					result = append(result, facts.Fact{
						Kind:  facts.KindRoute,
						Name:  currentPath,
						File:  relFile,
						Line:  i + 1,
						Props: props,
						Relations: []facts.Relation{
							{Kind: facts.RelDeclares, Target: specDir},
						},
					})
				}
			}
			depth += opens - closes
			if depth < 2 {
				currentPath = "" // exited the path entry block
			}

		default:
			// depth > 2: inside a nested sub-object (parameters, responses, etc.)
			depth += opens - closes
		}
	}

	return result
}
